### ISSUE TITLE
DateTime comparison with TZDateTime throws NoSuchMethodError

### ISSUE THREAD

**Issue by jkokkala** [srawlins/timezone#10]
The following line of code will cause a runtime error:
`new DateTime.now().isAfter(new TZDateTime.now(UTC))`

The error:
<pre>EXCEPTION: NoSuchMethodError: method not found: '<Unexpected Null Value>'
Receiver: null
Arguments: []
STACKTRACE: 
dart:core                                                    isAfter</pre>

This happens because DateTime.isAfter is using a private value `_value` to do the comparison but since TZDateTime only implements the interface, it has no privates that would be accessible. As mentioned in dart-lang/sdk#25462 there's not much this library can do about it since it's a language level problem which won't be caught by any compiler.

**Comment by srawlins** [comment]
More specifically, this is blocked by https://github.com/dart-lang/sdk/issues/32051.

**Comment by sir-boformer** [comment]
this is still an issue

**Comment by NightOwlCoder** [comment]
While the final fix from DART does not come, I've created this extension to help:
```
extension DateTimeExtensions on DateTime {
  DateTime clone({
    int year: null,
    int month: null,
    int day: null,
    int hour: null,
    int minute: null,
    int second: null,
    int millisecond: null,
    bool isUtc: null,
  }) {
    if (isUtc == null ? this.isUtc : isUtc) {
      return DateTime.utc(
        year == null ? this.year : year,
        month == null ? this.month : month,
        day == null ? this.day : day,
        hour == null ? this.hour : hour,
        minute == null ? this.minute : minute,
        second == null ? this.second : second,
        millisecond == null ? this.millisecond : millisecond,
      );
    }
    return DateTime(
      year == null ? this.year : year,
      month == null ? this.month : month,
      day == null ? this.day : day,
      hour == null ? this.hour : hour,
      minute == null ? this.minute : minute,
      second == null ? this.second : second,
      millisecond == null ? this.millisecond : millisecond,
    );
  }
}
```

PS it works perfect  to work around this bug, I changed the `TZDateTime` to a `DateTime` value on the last mile of my method...

**Comment by srawlins** [comment]
dart-lang/sdk#32051 is closed as fixed, and I do not see a stack trace any longer. I believe this is fixed.
