### ISSUE TITLE
Error Import Not Found Can't Run the App After adding 0.8.0 version

### ISSUE THREAD

**Issue by prithiviraj** [srawlins/timezone#115]
../../../Softwares/Engineering/flutter/.pub-cache/hosted/pub.dartlang.org/timezone-0.8.0/lib/browser.dart:16:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../../Softwares/Engineering/flutter/.pub-cache/hosted/pub.dartlang.org/intl-0.17.0/lib/intl_browser.dart:12:8: Error: Not found: 'dart:html'
import 'dart:html';

Please help me with this.

**Comment by SamoilovEA** [comment]
@prithiviraj Hi, have you solved this problem?

**Comment by Den-Ree** [comment]
Having the same issue

**Comment by Den-Ree** [comment]
@srawlins maybe you have ideas what it might be? 

@SamoilovEA @prithiviraj hi guys, did you find a way how to fix it?

**Comment by laksh97** [comment]
@srawlins Can you please look into it and help on the same?

@SamoilovEA @prithiviraj @Den-Ree Did you guys manage to fix it?

**Comment by asdasdasde** [comment]
If you are not targeting the browser, check that you have not accidentally imported the browser specific file:

`import 'package:timezone/browser.dart' as tz;`

Instead, you should use:

`import 'package:timezone/data/latest.dart' as tz;`

**Comment by laksh97** [comment]
Thanks, @asdasdasde, this solved the issue.

**Comment by srawlins** [comment]
Agreed; `browser.dart` imports `dart:html` which is not available on Flutter for iOS or Flutter for Android.
