### ISSUE TITLE
time zone doesn't exist

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [srawlins/timezone#117]
Pub version : **timezone: ^0.5.6**

We are receiving the below error while applying the below the region in the below code

**Europe/Nicosia
Europe/Tiraspol
Europe/Belfast**

```
import 'package:timezone/data/latest.dart' as tz;
import 'package:timezone/timezone.dart' as tz;

  DateTime getDateTime() {
    tz.initializeTimeZones();
    final detroit = tz.getLocation("Europe/Belfast");
    final DateTime dateTime = tz.TZDateTime.now(detroit);
    return dateTime;
  } 
```
![Untitled](https://user-images.githubusercontent.com/64843262/135572566-3f2c8ad6-0cb4-4097-bf59-209f55e16cd3.png)

**Comment by srawlins** [comment]
As these time zones are deprecated, they are not available in the default data base (e.g. `latest.dart`); they are available in the "all" variant (e.g. `latest_all.dart`).
