### ISSUE TITLE
Location with the name "Asia/Yangon" doesn't exist

### ISSUE THREAD

**Issue by JoelSuyati** [srawlins/timezone#118]
Location with the name "Asia/Yangon" doesn't exist

timezone: ^0.8.0 is the version I used

**Comment by JornaldRem** [comment]
I have the same issue. How did you solve it?

**Comment by zawhtetnaing10** [comment]
"Asia/Rangoon" did the trick for me.

**Comment by srawlins** [comment]
Is this an officially recognized time zone? Did you try [the 'all' variant](https://github.com/srawlins/timezone#initialization-from-dart-library)?
