### ISSUE TITLE
Timezone assets not loaded on aws ec2 server

### ISSUE THREAD

**Issue by Sasikumar3595** [srawlins/timezone#133]
We are creating a new widget with timezone package, and the package makes an error while loading the widget on aws ec2 server. 

**It shows the error below:**

Uncaught Unable to load asset: packages/timezone/data/2020a.tzf

**Error screenshots:** 

![Screen Shot 2022-04-22 at 4 47 38 PM](https://user-images.githubusercontent.com/44917578/164704529-92052b12-fe74-4ce0-bfef-87fa5604eead.png)

**Comment by Sasikumar3595** [comment]
@srawlins 

Any update/suggestion on this?

**Comment by Nijamudeen-Mohamed** [comment]
> We are creating a new widget with timezone package, and the package makes an error while loading the widget on aws ec2 server.
> 
> **It shows the error below:**
> 
> Uncaught Unable to load asset: packages/timezone/data/2020a.tzf
> 
> **Error screenshots:**
> 
> ![Screen Shot 2022-04-22 at 4 47 38 PM](https://user-images.githubusercontent.com/44917578/164704529-92052b12-fe74-4ce0-bfef-87fa5604eead.png)

Any update on this?

**Comment by Nijamudeen-Mohamed** [comment]
Hi Team,
Expecting a rapid solution to this. do the needful.

**Comment by srawlins** [comment]
Thanks for your question. Questions like this are better asked on a large programming forum like StackOverflow, with more eyes to look at a question. I cannot answer your question here without you are [initializing from the dart library](https://github.com/srawlins/timezone#initialization-from-dart-library), without seeing the initialization code, without knowing the version of the timezone package used. This would be good information to include in a post to StackOverflow. Also it would be good to indicate why you are requesting the 2020a database, and not the latest.

**Comment by Sasikumar3595** [comment]
@srawlins ,

**Code sample:**

```

@override
  void initState() {
    _loadDataBase();
    super.initState();
  }

  Future<bool> _loadDataBase() async {
    final ByteData byteData =
    await rootBundle.load('packages/timezone/data/2020a.tzf');
    initializeDatabase(byteData.buffer.asUint8List());
    return true;
  }

  void _refresh() {
    DateTime date = DateTime.now();
    Location location = getLocation('Australia/Darwin');
    DateTime convertedDate = TZDateTime.from(date, location);
    print(convertedDate);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(

        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _refresh,
        tooltip: 'Convert Date',
        child: const Icon(Icons.refresh),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

```

**TimeZone package:** timezone 0.8.0

**Note:**  It was working fine on other than aws ec2 servers.

**Comment by ranjithsan** [comment]
@srawlins 
please update on how this can be fixed...We are working on a crucial project and all was working fine during dev and  when we moved the code to aws..it stopped working.... your help is greatly appreciated...

**Comment by srawlins** [comment]
Sorry about the crucial project. Please try a user forum.

**Comment by Sasikumar3595** [comment]
@srawlins ,

We asked the same on StackOverFlow forum also
StackOverFlow link: https://stackoverflow.com/questions/72008671/widget-assets-are-not-loaded-on-aws-ec2-server

**Comment by hs-dev1** [comment]
https://github.com/syncfusion/flutter-examples/issues/450
