### ISSUE TITLE
Location with name "Asia/Katmandu" doesn't exist.

### ISSUE THREAD

**Issue by E-n-N-D** [srawlins/timezone#136]
The spelling "Katmandu" is a mistake. It must be "Kathmandu".

**Comment by Kristina-Isakovich** [comment]
Try using `import 'package:timezone/data/latest_all.dart' as tz;` instead of import `'package:timezone/data/latest.dart' as tz;`

**Comment by surveshoeb** [comment]
> Try using `import 'package:timezone/data/latest_all.dart' as tz;` instead of `import 'package:timezone/data/latest.dart' as tz;`

It works
