### ISSUE TITLE
EST5EDT doesn't exist.  By Design?

### ISSUE THREAD

**Issue by SApolinario** [srawlins/timezone#137]
I'm unable to retrieve the location for time zone "EST5EDT".  I believe it's included in the IANA database.  Is that by design?  Thanks.

**Comment by srawlins** [comment]
Is this an officially recognized time zone? Did you try [the 'all' variant](https://github.com/srawlins/timezone#initialization-from-dart-library)?

**Comment by arv-aks** [comment]
import 'package:timezone/data/latest_all.dart';

still unable to retrieve the location for the following timezones

  "(GMT+2:00) EET",
  "(GMT-5:00) EST",
  "(GMT-5:00) EST5EDT",
 "(GMT-5:00) Cuba",
  "(GMT+2:00) Egypt",
 "(GMT0:00) Eire",
  "(GMT0:00) Etc/GMT",
  "(GMT0:00) Etc/GMT+0",
  "(GMT-1:00) Etc/GMT+1",
  "(GMT-10:00 Etc/GMT+10",
  "(GMT-11:00) Etc/GMT+11",
  "(GMT-12:00) Etc/GMT+12",
  "(GMT-2:00) Etc/GMT+2",
  "(GMT-3:00) Etc/GMT+3",
  "(GMT-4:00) Etc/GMT+4",
  "(GMT-5:00) Etc/GMT+5",
  "(GMT-6:00) Etc/GMT+6",
  "(GMT-7:00) Etc/GMT+7",
  "(GMT-8:00) Etc/GMT+8",
  "(GMT-9:00) Etc/GMT+9",
  "(GMT0:00) Etc/GMT-0",
  "(GMT+1:00) Etc/GMT-1",
  "(GMT+10:00) Etc/GMT-10",
  "(GMT+11:00) Etc/GMT-11",
  "(GMT+12:00) Etc/GMT-12",
  "(GMT+13:00) Etc/GMT-13",
  "(GMT+14:00) Etc/GMT-14",
  "(GMT+2:00) Etc/GMT-2",
  "(GMT+3:00) Etc/GMT-3",
  "(GMT+4:00) Etc/GMT-4",
  "(GMT+5:00) Etc/GMT-5",
  "(GMT+6:00) Etc/GMT-6",
  "(GMT+7:00) Etc/GMT-7",
  "(GMT+8:00) Etc/GMT-8",
  "(GMT+9:00) Etc/GMT-9",
  "(GMT0:00) Etc/GMT0",
  "(GMT0:00) Etc/Greenwich",
  "(GMT0:00) Etc/UCT",
  "(GMT0:00) Etc/UTC",  //(GMT0:00) UTC
  "(GMT0:00) Etc/Universal",
  "(GMT0:00) Etc/Zulu",

**Comment by srawlins** [comment]
I just tried with the _all database in the 0.9.1 release and the following work:

* `getLocation('EST5EDT')`
* `getLocation('Cuba')`
* `getLocation('Egypt')`
* `getLocation('Etc/GMT')`
* `getLocation('Etc/UTC')`
