### ISSUE TITLE
2022c has just been released

### ISSUE THREAD

**Issue by RandalSchwartz** [srawlins/timezone#140]
Time for a refresh!

**Comment by jagiro** [comment]
Hi @srawlins, 

we would very much appreciate this refresh because App Stores take time to validates the Apps and in Chile the change applies at 4th of September.

Thanks in advance

**Comment by jagiro** [comment]
@srawlins thanks for your [quickly update](https://github.com/srawlins/timezone/pull/141)

But looks not published yet to [pub.dev](https://pub.dev/)

> Because [AppName] depends on timezone ^0.9.0 which doesn't match any versions, version solving failed.

**Comment by srawlins** [comment]
Released
