### ISSUE TITLE
Some of time zone is not supported.

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [srawlins/timezone#144]
i received below error while i set **Australia/LHI**

ERROR: Location with the name "Australia/LHI" doesn't exist

Location with the name "**Australia/South**" doesn't exist

**Australia/Canberra**

{
             "ACT": "Australia/ACT",
             "Adelaide": "Australia/Adelaide",
             "Brisbane": "Australia/Brisbane",
             "Broken_Hill": "Australia/Broken_Hill",
             "Canberra": "Australia/Canberra",
             "Currie": "Australia/Currie",
             "Darwin": "Australia/Darwin",
             "Eucla": "Australia/Eucla",
             "Hobart": "Australia/Hobart",
             "LHI": "Australia/LHI",
             "Lindeman": "Australia/Lindeman",
             "Lord_Howe": "Australia/Lord_Howe",
             "Melbourne": "Australia/Melbourne",
             "NSW": "Australia/NSW",
             "North": "Australia/North",
             "Perth": "Australia/Perth",
             "Queensland": "Australia/Queensland",
             "South": "Australia/South",
             "Sydney": "Australia/Sydney",
             "Tasmania": "Australia/Tasmania",
             "Victoria": "Australia/Victoria",
             "West": "Australia/West",
             "Yancowinna": "Australia/Yancowinna"
        }

most of region are not support

**Comment by MurtuzaSrashtaSoft** [comment]
![Screenshot 2022-10-09 at 5 45 42 PM](https://user-images.githubusercontent.com/64843262/194756323-74e2b07f-f789-4f12-ac2b-6322293742aa.png)

**Comment by MurtuzaSrashtaSoft** [comment]
https://github.com/srawlins/timezone/issues/138#issuecomment-1217623499

**Comment by srawlins** [comment]
Is this an officially recognized time zone? Did you try [the 'all' variant](https://github.com/srawlins/timezone#initialization-from-dart-library)?
