### ISSUE TITLE
"Europe/Kiev" - are to be changed into "Europe/Kyiv"

### ISSUE THREAD

**Issue by xeno-sama** [srawlins/timezone#145]
please revise it
"Europe/Kiev" - are to be changed into "Europe/Kyiv"

**Comment by srawlins** [comment]
We use the time zone database from IANA and will not deviate. If it is an official alias, that can be tracked at https://github.com/srawlins/timezone/issues/80.

**Comment by jeanantoine** [comment]
Hello,

Please update the time zone database from IANA to latest version: 2022g (Released 2022-11-29).
The change from Europe/Kiev to Europe/Kyiv has been taken into account.

tzdata2022g: 
`./NEWS:    Rename Europe/Kiev to Europe/Kyiv.`

https://www.iana.org/time-zones

File | Description
-- | --
tzdb-2022g.tar.lz (509.1kb) | Complete Distribution (Data, Code and Extras)
tzdata2022g.tar.gz (429.4kb) | Data Only Distribution
tzcode2022g.tar.gz (281.2kb) | Code Only Distribution

Latest version
2022g (Released 2022-11-29)
File 	Description
[tzdb-2022g.tar.lz](https://data.iana.org/time-zones/releases/tzdb-2022g.tar.lz) (509.1kb) 	Complete Distribution (Data, Code and Extras)
[tzdata2022g.tar.gz](https://data.iana.org/time-zones/releases/tzdata2022g.tar.gz) (429.4kb) 	Data Only Distribution
[tzcode2022g.tar.gz](https://data.iana.org/time-zones/releases/tzcode2022g.tar.gz) (281.2kb) 	Code Only Distribution
https://data.iana.org/time-zones/releases/tzdata2022g.tar.gz
