### ISSUE TITLE
error when run in iOS

### ISSUE THREAD

**Issue by artk12** [srawlins/timezone#171]
Error: Dart library 'dart:html' is not available on this platform.

**Comment by mathisfouques** [comment]
For sure on ios you should only call dart:io ; what's the function which throw the error ? thanks

**Comment by hayesOw** [comment]
I had the same issue browser.dart from the library got added to my imports. removing that fixed it

**Comment by armagangok** [comment]
@hayesOw  What do you mean exactly? I am having the same issue

**Comment by srawlins** [comment]
`dart:html` is no longer used, as of https://github.com/srawlins/timezone/pull/194
