### ISSUE TITLE
Conversion from local DateTime objects

### ISSUE THREAD

**Issue by tomaine2002** [srawlins/timezone#18]
The _native DateTime is [expected](https://github.com/srawlins/timezone/blob/06e613a4a75f2262bf1a68b54e77b0d78f5945f1/lib/src/date_time.dart#L45) to be UTC.

[This constructor](https://github.com/srawlins/timezone/blob/06e613a4a75f2262bf1a68b54e77b0d78f5945f1/lib/src/date_time.dart#L195) accepts any DateTime, which may or may not be in UTC.

When a non-UTC DateTime is provided, we incorrectly adjust the native DateTime by the offset from UTC to generate the _localDateTime. For example, if the caller passes a DateTime whose offset is the same as the location, then _native and _localDateTime should be the same instant, and no offset should be added. However, the current code always applies the offset from UTC.

The TZDateTime.now() constructor calls [DateTime.now()](https://api.dartlang.org/stable/2.0.0/dart-core/DateTime/DateTime.now.html), which generates a DateTime in the local timezone (likely not UTC), triggering this bug.

Ways to repro (these should repro the bug when the local timezone is not UTC):
1. Call TZDateTime.now().
2. Call TZDateTime.from with a DateTime generated via [this constructor](https://api.dartlang.org/stable/2.0.0/dart-core/DateTime/DateTime.html).

**Comment by srawlins** [comment]
What a weird bug to have existed for so long 😛 . You are correct though. I guess it's usually used with UTC timezones? Or people don't use the `.from` constructor a lot?
