### ISSUE TITLE
Kazakhstan switched to a single time

### ISSUE THREAD

**Issue by Kristina-Isakovich** [srawlins/timezone#188]
On the night of February 29 to March 1, 2024, UTC+5 time was set throughout Kazakhstan.
But your time is UTC+6.

**Comment by n0mad-d3v** [comment]
This should be fixed by the (currently opened) PR: https://github.com/srawlins/timezone/pull/187 as it's part of the announced changes of the 2024a database.

**Comment by Kristina-Isakovich** [comment]
Could you please upload the latest changes to pub.dev?

**Comment by fatherOfLegends** [comment]
@srawlins or @n0mad-d3v can we please get a release or a response about when the next release will be?

**Comment by srawlins** [comment]
Apologies, published as timezone 0.9.3.
