### ISSUE TITLE
Upgrade JS interop by removing dart:html dependency

### ISSUE THREAD

**Issue by maxlapides** [srawlins/timezone#193]
"The Dart team recently overhauled the collection of features and APIs that allow developers access to JavaScript and browser bindings in their Dart code. This next generation of web interop not only improves user experience, but also enables Wasm support, aligning Dart with the future of the Web."

https://dart.dev/interop/js-interop

Looks like there is only one file that is using `dart:html`:
https://github.com/srawlins/timezone/blob/master/lib/browser.dart#L16

**Comment by srawlins** [comment]
Fixed by https://github.com/srawlins/timezone/pull/194
