### ISSUE TITLE
remove dart:html import and do network request via http

### ISSUE THREAD

**Issue by bsb-github** [srawlins/timezone#203]
the dart:html is causing error when import browser.dart file

**Comment by zmuranaka** [comment]
Also no Flutter packages are recommended to use `dart:html` anymore.

See [here](https://dart.dev/interop/js-interop/package-web)

![image](https://github.com/user-attachments/assets/7b30e2c3-d337-435c-b3e9-1da028d9c4e8)

**Comment by denfrancis** [comment]
When will this be fixed? The package is unusable on any mobile platform.

**Comment by srawlins** [comment]
Done in https://github.com/srawlins/timezone/pull/194
