### ISSUE TITLE
 Error: Dart library 'dart:html' is not available on this platform.

### ISSUE THREAD

**Issue by armagangok** [srawlins/timezone#204]
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/timezone-0.9.4/lib/browser.dart:16:8: Error: Dart library 'dart:html' is not available on this platform.

iOS 17.6.1. iPhone 15 pro

**Comment by zmuranaka** [comment]
[dart:html](https://dart.dev/libraries/dart-html) is a Dart library that is only supported for web apps. Since you are building Flutter for iOS, it will not compile if you import `browser.dart`.

**Comment by daria-ost-embrox** [comment]
Any updates here?
I faced the same issue

**Comment by srawlins** [comment]
@daria-ost-embrox  no update. Why do you need to import browser.dart?

**Comment by srawlins** [comment]
`dart:html` no longer used, as of https://github.com/srawlins/timezone/pull/194.
