### ISSUE TITLE
Some timezones are not being recognized

### ISSUE THREAD

**Issue by jezer07** [srawlins/timezone#37]
Hi, we have a list of timezones that I believe came from:
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Some of these timezones are not being recognized by the plugin like: "GMT", "PRC" "Etc/GMT" when we pass them to `setLocalLocation`

It's saying:
`Unhandled Exception: Location with the name "PRC" doesn't exist`

But our web app can recognized those timezones. They're using `momentjs` which is also based on IANA.

Any idea on this? Thanks.

**Comment by krolaw** [comment]
The instructions explicitly state abbreviated zone names are not supported due to "ambiguities". I'd guess if you want them, you'll need to alias them yourself.

**Comment by srawlins** [comment]
Have you tried the "all" database? E.g. `2019b_all.tzf` or `latest_all.tzf`?

**Comment by workerbee22** [comment]
So what is the recommended way to determine valid locations?

**Comment by workerbee22** [comment]
So to help out others, the valid locations for ```setLocalLocation``` or ```getLocation``` method call is something like this:

1. Uncompress the Timezone data file eg. ```tzdata2019c.tar.gz```

2. From the uncompressed files, select one of the various regional files like ```northamerica``` Note the files have no extensions but are text files

3. These files are large ie. ```northamerica``` is > 3500 lines. But take a guess and try to find the largest city/state/region to search by. For example I needed PST timezone for San Francisco but searched for Los Angeles and found this:

![image](https://user-images.githubusercontent.com/5154664/72144073-9cd4b580-33e3-11ea-86e9-904a0bb8bcef.png)

4. The Zone line is what you are looking for, so for example the valid location I needed was ```'America/Los_Angeles'```

**Comment by workerbee22** [comment]
This should be mentioned in the documentation 👍

**Comment by srawlins** [comment]
Apologies for being, um, very late to this party.

> Some of these timezones are not being recognized by the plugin like: "GMT", "PRC" "Etc/GMT" when we pass them to setLocalLocation

* "PRC" is listed as being deprecated; it won't be found.
* "GMT" is an _alias_ for "Etc/GMT"; the latter should be used.
* "Etc/GMT" is only found in the _all_ database.

I've just added some better docs to README to help with this.
