### ISSUE TITLE
DST info

### ISSUE THREAD

**Issue by Jeremywhiteley** [srawlins/timezone#44]
Is it possible to get the date when DST changes for a timezone?   The start and stop dates?

**Comment by srawlins** [comment]
The current API has no functionality for this. If another package offers such functionality (e.g. a Java, Python, Ruby, Node, etc. package), I could try to copy it.

**Comment by Jeremywhiteley** [comment]
https://momentjs.com/

It’s needed.  I can’t find anything for Dart.

**Comment by srawlins** [comment]
If that website address is a hint about a package that offers such functionality to get the date when DST changes, I will need more than that. Sorry, I can't go on a wild goose chase when someone casually drops a website address.

**Comment by Jeremywhiteley** [comment]
Let me explain a bit more.   

Sometimes, you need to be able to determine when Daylight Savings Time (DST) will occur in a given year. DST varies around the world for timezones where DST is observed.  

-https://www.codeproject.com/Articles/58728/JavaScript-Code-to-Determine-When-DayLight-Savings
- https://optimalbi.com/blog/2017/11/21/times-and-timezones-in-nodejs-using-moment-js/
- https://momentjs.com/timezone/docs/
- https://github.com/moment/moment-timezone/


Momentjs  is using the Release 0.5.27 - IANA 2019c.  I think you are too.   So the data is stored that file.  Just need to way to get it out using dart.     If you copied the momentjs for node, you would have the most popular timezone plugin.   

What I need is the start and stop dates for Daylight savings for each time zone.

**Comment by srawlins** [comment]
Sorry, I'm still having trouble seeing where moment.js tells the user when DST changes for a timezone. I looked through all of your links. You can copy the implementation from [1] though. Here's a start:

```dart
import 'package:timezone/standalone.dart';
import 'package:timezone/data/latest.dart';

void main() {
  initializeTimeZones();
  var detroit = getLocation('America/Detroit');
  var now = TZDateTime.now(detroit);
  var year = now.year;
  for (var month = 0; month < 12; month++) {
    var firstOfTheMonth = TZDateTime(detroit, year, month);
    print('${month + 1}-$year: ${firstOfTheMonth.timeZoneOffset}');
  }
  var nextYear = year + 1;
  var firstOfTheNextYear = TZDateTime(detroit, nextYear, 0);
  print('1-$nextYear: ${firstOfTheNextYear.timeZoneOffset}');
}
```

Executing this prints:

```none
1-2020: -5:00:00.000000
2-2020: -5:00:00.000000
3-2020: -5:00:00.000000
4-2020: -5:00:00.000000
5-2020: -4:00:00.000000
6-2020: -4:00:00.000000
7-2020: -4:00:00.000000
8-2020: -4:00:00.000000
9-2020: -4:00:00.000000
10-2020: -4:00:00.000000
11-2020: -4:00:00.000000
12-2020: -4:00:00.000000
1-2021: -5:00:00.000000
```

You can tell that DST starts in December, and ends in April.

[1] https://www.codeproject.com/Articles/58728/JavaScript-Code-to-Determine-When-DayLight-Savings
