### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by AdnanKazi** [srawlins/timezone#45]
After I run this command it shows me error `flutter pub run tool/get -s 2019c
`
Please help me out

```
CreateProcessW failed 2
INFO: 2019-11-25 15:36:03.771047: Cleaning up temporary directories
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: zic -d C:\Users\Micra\AppData\Local\Temp\tzdata-2c5a5dae-0f6b-11ea-8a0d-00a0c6000010\zic C:\Users\Micra\AppData\Local\Temp\tzdata-2c5a5dae-0f6b-11ea-8a0d-00a0c6000010\af
rica
#0      zic (file:///F:/AdnanWorkspace/flutter/.pub-cache/hosted/pub.dartlang.org/timezone-0.5.5/tool/get.dart:80:18)
<asynchronous suspension>
#1      main (file:///F:/AdnanWorkspace/flutter/.pub-cache/hosted/pub.dartlang.org/timezone-0.5.5/tool/get.dart:122:13)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
pub failed (255)

```

**Comment by krolaw** [comment]
I have the same problem on Ubuntu:
```bash
$ flutter pub run tool/get -s 2014h
Could not find tool/get.dart.
pub failed (66)
```

**Comment by krolaw** [comment]
Actually I suspect the only reason we are attempting to run the tool is because we are getting this error when attempting to run:
Error detected in pubspec.yaml:
No file or variants found for asset: packages/timezone/data/latest.tzf.

**Comment by srawlins** [comment]
@AdnanKazi I think the Time Zone database URL changed; I fixed this in https://github.com/srawlins/timezone/commit/d958d6f50c0ba8650ccb2743651a7ef5b5fb0b8b, which will come in version 0.5.6. Please re-open if you continue to get this bug.

**Comment by D-Elyes** [comment]
Hello @srawlins , i tried to run the command and i'm getting the same error

**Comment by srawlins** [comment]
@D-Elyes would you mind opening a new bug with the command you run and the output you see?

**Comment by D-Elyes** [comment]
@srawlins Yes.
thank you
