### ISSUE TITLE
how to get current local timezone on web?

### ISSUE THREAD

**Issue by PhloxDev** [srawlins/timezone#67]
I want to get current timezone name like Europe/london.
how to get it?

**Comment by srawlins** [comment]
@PhloxDev there is documentation in README.md. Specifically this section shows an example of getting a time zone by name: https://github.com/srawlins/timezone#initialization-for-browser-environment.

**Comment by scopendo** [comment]
I don't think this question has been answered.  It's clear how to get the time zone object for an IANA time zone id such as America/Detroit, but the question appears to be asking how to get the time zone id itself in a web environment.

**Comment by enyo** [comment]
So I've looked around, and I don't think there is a way to get it with this library. If you're on web, then you need to use the [ECMAScript Internationalization API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl). I don't think that there is a dart implementation for it, but you can simply write your [JavaScript interop code](https://github.com/pinkfish/flutter_native_timezone/blob/343e5e2af7dbf9a630b729a187eb2ad6e696ca89/lib/flutter_native_timezone_web.dart#L45) for it.

If you're using flutter, then the package `flutter_native_timezone` can expose it for you, and it [now supports web](https://pub.dev/packages/flutter_native_timezone/changelog#1012) as well.
