### ISSUE TITLE
Location with the name "Asia/Chongqing" doesn't exist.

### ISSUE THREAD

**Issue by lanistor** [srawlins/timezone#75]
Get location name by `flutter_native_timezone`:
```dart
currentTimeZone = await FlutterNativeTimezone.getLocalTimezone();
tz.initializeTimeZones();
var loc = tz.getLocation(currentTimeZone);
tz.setLocalLocation(loc);
```
Users report the error (iPhone device), i get it's because the `tz.timeZoneDatabase.locations` doesn't contains `Asia/Chongqing` the got by `flutter_native_timezone`. 

What should i do to resolve it?
I think there's a way: get nearest location of `Asia/Chongqing`, by for other locations, how to automaticlly map them?

**Comment by faisalmushtaq007** [comment]
Unhandled Exception: Location with the name "Asia/Calcutta" doesn't exist
any solutions????

**Comment by DominicOrga** [comment]
I was able to use deprecated locations by importing 'package:timezone/data/latest_all.dart' instead of 'package:timezone/data/latest.dart'.

**Comment by Jayvd** [comment]
@lanistor @faisalmushtaq007 Did you find a solution to this problem?

**Comment by srawlins** [comment]
Apologies for the late response. Both Asia/Chongqing and Asia/Calcutta are available in latest_all.

**Comment by MrCsabaToth** [comment]
How do you call `tz.getLocation(` while `'package:timezone/data/latest_all.dart'` only provides one function `initializeTimeZones`?
