### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The method 'timeZone' was called on null.

### ISSUE THREAD

**Issue by drexhacker** [srawlins/timezone#91]

**Comment by armandojimenez** [comment]
getting the same

**Comment by talwarabhimanyu** [comment]
I'm getting the same error. Here is how I am using the package. Kindly help.

```
import 'package:timezone/data/latest.dart' as tz;
import 'package:timezone/timezone.dart' as tz;

void main async {
  tz.initializeTimeZones();
  tz.setLocalLocation(tz.getLocation(await FlutterNativeTimezone.getLocalTimezone()));
  runApp(App());
}

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  var notifyTime = tz.TZDateTime.now(tz.local).add(Duration(seconds: 10));
}
```

**Comment by talwarabhimanyu** [comment]
I added the following line as the first statement inside `main` and the error stopped appearing. It seems this is required if we are awaiting a Future inside main.
```
WidgetsFlutterBinding.ensureInitialized();
```

I took this suggestion from [this StackOverflow link](https://stackoverflow.com/questions/57689492/flutter-unhandled-exception-servicesbinding-defaultbinarymessenger-was-accesse).

**Comment by srawlins** [comment]
Apologies for the late reply. In addition to the repro code, can someone provide a stack trace? The repro code in the last comment does not call `timeZone`.

**Comment by srawlins** [comment]
Closing; please open a new issue with details if it occurs again.
